# Generated by Django 5.1 on 2024-09-19 22:22

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='TopTrader',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('coin', models.CharField(max_length=256, verbose_name='Монета')),
                ('coin_address', models.CharField(max_length=256, verbose_name='Адрес монеты')),
                ('pair', models.CharField(max_length=256, verbose_name='Pair')),
                ('maker', models.CharField(max_length=256, verbose_name='Кошелёк')),
                ('chain', models.CharField(max_length=256, verbose_name='Сеть')),
                ('bought', models.IntegerField(verbose_name='Купил')),
                ('sold', models.IntegerField(verbose_name='Продал')),
                ('PNL', models.FloatField(verbose_name='PNL')),
                ('created_date', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'verbose_name': 'Топ кошельков',
                'verbose_name_plural': 'Топ кошельков',
            },
        ),
        migrations.CreateModel(
            name='Transaction',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('pair', models.CharField(max_length=256, verbose_name='Pair')),
                ('coin', models.CharField(max_length=256, verbose_name='Монета')),
                ('coin_address', models.CharField(max_length=256, verbose_name='Адрес')),
                ('buying_price', models.FloatField(verbose_name='Цена покупки')),
                ('current_price', models.FloatField(blank=True, null=True, verbose_name='Текущая цена')),
                ('selling_price', models.FloatField(blank=True, null=True, verbose_name='Цена продажи')),
                ('opening_date', models.DateTimeField(auto_now_add=True, verbose_name='Время покупки')),
                ('closing_date', models.DateTimeField(blank=True, null=True, verbose_name='Время продажи')),
                ('PNL', models.DecimalField(blank=True, decimal_places=2, max_digits=12, null=True, verbose_name='PNL')),
                ('status', models.CharField(choices=[('open', 'Открытая'), ('closed', 'Закрытая')], default='open', max_length=64, verbose_name='Статус')),
            ],
            options={
                'verbose_name': 'Транзакция',
                'verbose_name_plural': 'Транзакции',
            },
        ),
    ]
