# Generated by Django 5.1 on 2024-09-21 21:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cointer', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='transaction',
            name='current_price',
        ),
        migrations.AddField(
            model_name='transaction',
            name='buying_fdv',
            field=models.FloatField(blank=True, null=True, verbose_name='FDV на момент покупки'),
        ),
        migrations.AddField(
            model_name='transaction',
            name='buying_liquidity',
            field=models.FloatField(blank=True, null=True, verbose_name='Ликвидность на момент покупки (5 минут)'),
        ),
        migrations.AddField(
            model_name='transaction',
            name='buying_market_cap',
            field=models.FloatField(blank=True, null=True, verbose_name='Рыночная капитализация на момент покупки'),
        ),
        migrations.AddField(
            model_name='transaction',
            name='buying_price_change_h1',
            field=models.IntegerField(blank=True, null=True, verbose_name='Изменение цены на момент покупки (5 минут)'),
        ),
        migrations.AddField(
            model_name='transaction',
            name='buying_price_change_m5',
            field=models.IntegerField(blank=True, null=True, verbose_name='Изменение цены на момент покупки (5 минут)'),
        ),
        migrations.AddField(
            model_name='transaction',
            name='buying_transactions_buys_h1',
            field=models.IntegerField(blank=True, null=True, verbose_name='Количество транзакций на момент покупки (1 час)'),
        ),
        migrations.AddField(
            model_name='transaction',
            name='buying_transactions_buys_m5',
            field=models.IntegerField(blank=True, null=True, verbose_name='Количество покупок на момент покупки (5 минут)'),
        ),
        migrations.AddField(
            model_name='transaction',
            name='buying_transactions_sells_h1',
            field=models.IntegerField(blank=True, null=True, verbose_name='Количество транзакций на момент покупки (1 час)'),
        ),
        migrations.AddField(
            model_name='transaction',
            name='buying_transactions_sells_m5',
            field=models.IntegerField(blank=True, null=True, verbose_name='Количество продаж на момент покупки (5 минут)'),
        ),
        migrations.AddField(
            model_name='transaction',
            name='buying_volume_h1',
            field=models.IntegerField(blank=True, null=True, verbose_name='Объём торгов на момент покупки (1 час)'),
        ),
        migrations.AddField(
            model_name='transaction',
            name='buying_volume_m5',
            field=models.IntegerField(blank=True, null=True, verbose_name='Объём торгов на момент покупки (5 минут)'),
        ),
        migrations.AddField(
            model_name='transaction',
            name='is_telegram',
            field=models.BooleanField(default=False, verbose_name='Наличие Телеграма'),
        ),
        migrations.AddField(
            model_name='transaction',
            name='is_twitter',
            field=models.BooleanField(default=False, verbose_name='Наличие Твиттера'),
        ),
        migrations.AddField(
            model_name='transaction',
            name='is_website',
            field=models.BooleanField(default=False, verbose_name='Наличие сайта'),
        ),
    ]
