# Generated by Django 5.1 on 2024-09-22 21:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cointer', '0002_remove_transaction_current_price_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='transaction',
            name='buying_coin_age',
            field=models.FloatField(default=0, verbose_name='Возраст на момент покупки'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='transaction',
            name='selling_coin_age',
            field=models.FloatField(default=0, verbose_name='Возраст на момент продажи'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='transaction',
            name='selling_fdv',
            field=models.FloatField(blank=True, null=True, verbose_name='FDV на момент продажи'),
        ),
        migrations.AddField(
            model_name='transaction',
            name='selling_liquidity',
            field=models.FloatField(blank=True, null=True, verbose_name='Ликвидность на момент продажи (5 минут)'),
        ),
        migrations.AddField(
            model_name='transaction',
            name='selling_market_cap',
            field=models.FloatField(blank=True, null=True, verbose_name='Рыночная капитализация на момент продажи'),
        ),
        migrations.AddField(
            model_name='transaction',
            name='selling_price_change_h1',
            field=models.IntegerField(blank=True, null=True, verbose_name='Изменение цены на момент продажи (1 час)'),
        ),
        migrations.AddField(
            model_name='transaction',
            name='selling_price_change_m5',
            field=models.IntegerField(blank=True, null=True, verbose_name='Изменение цены на момент продажи (5 минут)'),
        ),
        migrations.AddField(
            model_name='transaction',
            name='selling_transactions_buys_h1',
            field=models.IntegerField(blank=True, null=True, verbose_name='Количество покупок на момент продажи (1 час)'),
        ),
        migrations.AddField(
            model_name='transaction',
            name='selling_transactions_buys_m5',
            field=models.IntegerField(blank=True, null=True, verbose_name='Количество покупок на момент продажи (5 минут)'),
        ),
        migrations.AddField(
            model_name='transaction',
            name='selling_transactions_sells_h1',
            field=models.IntegerField(blank=True, null=True, verbose_name='Количество продаж на момент продажи (1 час)'),
        ),
        migrations.AddField(
            model_name='transaction',
            name='selling_transactions_sells_m5',
            field=models.IntegerField(blank=True, null=True, verbose_name='Количество продаж на момент продажи (5 минут)'),
        ),
        migrations.AddField(
            model_name='transaction',
            name='selling_volume_h1',
            field=models.IntegerField(blank=True, null=True, verbose_name='Объём торгов на момент продажи (1 час)'),
        ),
        migrations.AddField(
            model_name='transaction',
            name='selling_volume_m5',
            field=models.IntegerField(blank=True, null=True, verbose_name='Объём торгов на момент продажи (5 минут)'),
        ),
        migrations.AlterField(
            model_name='transaction',
            name='buying_price_change_h1',
            field=models.IntegerField(blank=True, null=True, verbose_name='Изменение цены на момент покупки (1 час)'),
        ),
        migrations.AlterField(
            model_name='transaction',
            name='buying_transactions_buys_h1',
            field=models.IntegerField(blank=True, null=True, verbose_name='Количество покупок на момент покупки (1 час)'),
        ),
        migrations.AlterField(
            model_name='transaction',
            name='buying_transactions_sells_h1',
            field=models.IntegerField(blank=True, null=True, verbose_name='Количество продаж на момент покупки (1 час)'),
        ),
    ]
