# Generated by Django 5.1 on 2024-09-22 21:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cointer', '0003_transaction_buying_coin_age_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='transaction',
            name='selling_coin_age',
            field=models.FloatField(blank=True, null=True, verbose_name='Возраст на момент продажи'),
        ),
    ]
