# Generated by Django 5.1 on 2024-09-28 16:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cointer', '0005_transaction_buying_total_transactions_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='transaction',
            name='status',
            field=models.CharField(choices=[('test', 'Тестирование'), ('emulation', 'Эмуляция'), ('real', 'Закрытая')], default='test', max_length=64, verbose_name='Тип'),
        ),
    ]
