# Generated by Django 5.1 on 2024-09-28 16:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cointer', '0006_alter_transaction_status'),
    ]

    operations = [
        migrations.AddField(
            model_name='transaction',
            name='type',
            field=models.CharField(choices=[('test', 'Тестирование'), ('emulation', 'Эмуляция'), ('real', 'Закрытая')], default='test', max_length=64, verbose_name='Тип'),
        ),
        migrations.AlterField(
            model_name='transaction',
            name='status',
            field=models.CharField(choices=[('open', 'Открытая'), ('closed', 'Закрытая')], default='open', max_length=64, verbose_name='Статус'),
        ),
    ]
