# Generated by Django 5.1 on 2024-08-17 17:53

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='TopTrader',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('coin', models.CharField(max_length=256, verbose_name='Монета')),
                ('maker', models.CharField(max_length=256, verbose_name='Кошелёк')),
                ('chain', models.CharField(max_length=256, verbose_name='Сеть')),
                ('bought', models.IntegerField(verbose_name='Купил')),
                ('sold', models.IntegerField(verbose_name='Продал')),
                ('PNL', models.FloatField(verbose_name='PNL')),
                ('created_date', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'verbose_name': 'Топ трейдеры',
                'verbose_name_plural': 'Топ трейдер',
            },
        ),
    ]
