# Generated by Django 5.1 on 2024-08-20 21:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('toss_a_coin', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='toptrader',
            name='pair',
            field=models.CharField(default='pair', max_length=256, verbose_name='Pair'),
            preserve_default=False,
        ),
    ]
