# Generated by Django 5.1 on 2024-09-12 21:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('toss_a_coin', '0002_toptrader_pair'),
    ]

    operations = [
        migrations.CreateModel(
            name='Transaction',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('coin', models.CharField(max_length=256, verbose_name='Монета')),
                ('coin_address', models.CharField(max_length=256, verbose_name='Адрес')),
                ('buying_price', models.FloatField(verbose_name='Цена покупки')),
                ('current_price', models.FloatField(blank=True, null=True, verbose_name='Текущая цена')),
                ('selling_price', models.FloatField(blank=True, null=True, verbose_name='Цена продажи')),
                ('opening_date', models.DateTimeField(auto_now_add=True, verbose_name='Время покупки')),
                ('closing_date', models.DateTimeField(blank=True, null=True, verbose_name='Время продажи')),
                ('PNL', models.FloatField(blank=True, null=True, verbose_name='PNL')),
                ('status', models.CharField(choices=[('open', 'Открытая'), ('closed', 'Закрытая')], default='open', max_length=64, verbose_name='Статус')),
            ],
            options={
                'verbose_name': 'Транзакция',
                'verbose_name_plural': 'Транзакции',
            },
        ),
        migrations.AlterModelOptions(
            name='toptrader',
            options={'verbose_name': 'Топ кошельков', 'verbose_name_plural': 'Топ кошельков'},
        ),
        migrations.AddField(
            model_name='toptrader',
            name='coin_address',
            field=models.CharField(default='hello', max_length=256, verbose_name='Адрес монеты'),
            preserve_default=False,
        ),
    ]
