# Generated by Django 5.1 on 2024-09-16 20:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('toss_a_coin', '0003_transaction_alter_toptrader_options_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='transaction',
            name='PNL',
            field=models.FloatField(blank=True, default=0, null=True, verbose_name='PNL'),
        ),
    ]
