# Generated by Django 5.1 on 2024-09-18 20:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('toss_a_coin', '0006_alter_transaction_pnl'),
    ]

    operations = [
        migrations.AddField(
            model_name='transaction',
            name='pair',
            field=models.CharField(default='None', max_length=256, verbose_name='Pair'),
            preserve_default=False,
        ),
    ]
