# Generated by Django 5.1 on 2024-08-13 21:35

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='TopTrader',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('coin', models.CharField(max_length=256, verbose_name='Монета')),
                ('trader', models.CharField(max_length=256, verbose_name='Трейдер')),
                ('bought', models.FloatField(verbose_name='Купил')),
                ('sold', models.FloatField(verbose_name='Продал')),
                ('PNL', models.FloatField(verbose_name='PNL')),
            ],
            options={
                'verbose_name': 'Топ трейдеры',
                'verbose_name_plural': 'Топ трейдер',
            },
        ),
    ]
