# Generated by Django 5.1 on 2024-08-14 19:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('parser', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='toptrader',
            name='trader',
        ),
        migrations.AddField(
            model_name='toptrader',
            name='maker',
            field=models.CharField(default='hello', max_length=256, verbose_name='Кошелёк'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='toptrader',
            name='network',
            field=models.CharField(default='sol', max_length=256, verbose_name='Сеть'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='toptrader',
            name='bought',
            field=models.IntegerField(verbose_name='Купил'),
        ),
        migrations.AlterField(
            model_name='toptrader',
            name='sold',
            field=models.IntegerField(verbose_name='Продал'),
        ),
    ]
