# Generated by Django 5.1 on 2024-08-15 18:59

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('parser', '0002_remove_toptrader_trader_toptrader_maker_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='toptrader',
            old_name='network',
            new_name='chain',
        ),
    ]
