# Generated by Django 5.1 on 2024-10-08 19:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('token_hunter', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='toptrader',
            name='maker',
        ),
        migrations.AddField(
            model_name='toptrader',
            name='wallet_address',
            field=models.CharField(default='address', max_length=256, verbose_name='Адрес кошелька'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='transaction',
            name='snipers_bought_1000_2500',
            field=models.FloatField(blank=True, null=True, verbose_name='Снайперы, купившие на 1000$ - 2500$'),
        ),
        migrations.AddField(
            model_name='transaction',
            name='snipers_bought_100_500',
            field=models.FloatField(blank=True, null=True, verbose_name='Снайперы, купившие на 100$ - 500$'),
        ),
        migrations.AddField(
            model_name='transaction',
            name='snipers_bought_100_less',
            field=models.FloatField(blank=True, null=True, verbose_name='Снайперы, купившие меньше, чем на 100$'),
        ),
        migrations.AddField(
            model_name='transaction',
            name='snipers_bought_2500_5000',
            field=models.FloatField(blank=True, null=True, verbose_name='Снайперы, купившие на 2500$ - 5000$'),
        ),
        migrations.AddField(
            model_name='transaction',
            name='snipers_bought_5000_more',
            field=models.FloatField(blank=True, null=True, verbose_name='Снайперы, купившие больше, чем на 5000$'),
        ),
        migrations.AddField(
            model_name='transaction',
            name='snipers_bought_500_1000',
            field=models.FloatField(blank=True, null=True, verbose_name='Снайперы, купившие на 500$ - 1000$'),
        ),
        migrations.AddField(
            model_name='transaction',
            name='snipers_held_all',
            field=models.FloatField(blank=True, null=True, verbose_name='Снайперы, которые держат'),
        ),
        migrations.AddField(
            model_name='transaction',
            name='snipers_no_bought',
            field=models.FloatField(blank=True, null=True, verbose_name='Снайперы без покупки'),
        ),
        migrations.AddField(
            model_name='transaction',
            name='snipers_pnl_1000_2500',
            field=models.FloatField(blank=True, null=True, verbose_name='Снайперы с PNL 1000$ - 2500$'),
        ),
        migrations.AddField(
            model_name='transaction',
            name='snipers_pnl_100_500',
            field=models.FloatField(blank=True, null=True, verbose_name='Снайперы с PNL 100$ - 500$'),
        ),
        migrations.AddField(
            model_name='transaction',
            name='snipers_pnl_100_less',
            field=models.FloatField(blank=True, null=True, verbose_name='Снайперы с PNL меньше, чем на 100$'),
        ),
        migrations.AddField(
            model_name='transaction',
            name='snipers_pnl_2500_5000',
            field=models.FloatField(blank=True, null=True, verbose_name='Снайперы с PNL 2500$ - 5000$'),
        ),
        migrations.AddField(
            model_name='transaction',
            name='snipers_pnl_5000_more',
            field=models.FloatField(blank=True, null=True, verbose_name='Снайперы с PNL больше, чем 5000$'),
        ),
        migrations.AddField(
            model_name='transaction',
            name='snipers_pnl_500_1000',
            field=models.FloatField(blank=True, null=True, verbose_name='Снайперы с PNL 500$ - 1000$'),
        ),
        migrations.AddField(
            model_name='transaction',
            name='snipers_pnl_loss',
            field=models.FloatField(blank=True, null=True, verbose_name='Снайперы с отрицательным PNL'),
        ),
        migrations.AddField(
            model_name='transaction',
            name='snipers_pnl_profit',
            field=models.FloatField(blank=True, null=True, verbose_name='Снайперы с положительным PNL'),
        ),
        migrations.AddField(
            model_name='transaction',
            name='snipers_sold_1000_2500',
            field=models.FloatField(blank=True, null=True, verbose_name='Снайперы, продавшие на 1000$ - 2500$'),
        ),
        migrations.AddField(
            model_name='transaction',
            name='snipers_sold_100_500',
            field=models.FloatField(blank=True, null=True, verbose_name='Снайперы, продавшие на 100$ - 500$'),
        ),
        migrations.AddField(
            model_name='transaction',
            name='snipers_sold_100_less',
            field=models.FloatField(blank=True, null=True, verbose_name='Снайперы, продавшие меньше, чем на 100$'),
        ),
        migrations.AddField(
            model_name='transaction',
            name='snipers_sold_2500_5000',
            field=models.FloatField(blank=True, null=True, verbose_name='Снайперы, продавшие на 2500$ - 5000$'),
        ),
        migrations.AddField(
            model_name='transaction',
            name='snipers_sold_5000_more',
            field=models.FloatField(blank=True, null=True, verbose_name='Снайперы, продавшие больше, чем на 5000$'),
        ),
        migrations.AddField(
            model_name='transaction',
            name='snipers_sold_500_1000',
            field=models.FloatField(blank=True, null=True, verbose_name='Снайперы, продавшие на 500$ - 1000$'),
        ),
        migrations.AddField(
            model_name='transaction',
            name='snipers_sold_all',
            field=models.FloatField(blank=True, null=True, verbose_name='Снайперы, продавшие всё'),
        ),
        migrations.AddField(
            model_name='transaction',
            name='snipers_sold_some',
            field=models.FloatField(blank=True, null=True, verbose_name='Снайперы, продавшие часть'),
        ),
        migrations.AddField(
            model_name='transaction',
            name='top_traders_bought_1000_2500',
            field=models.FloatField(blank=True, null=True, verbose_name='Топы, купившие на 1000$ - 2500$'),
        ),
        migrations.AddField(
            model_name='transaction',
            name='top_traders_bought_100_500',
            field=models.FloatField(blank=True, null=True, verbose_name='Топы, купившие на 100$ - 500$'),
        ),
        migrations.AddField(
            model_name='transaction',
            name='top_traders_bought_100_less',
            field=models.FloatField(blank=True, null=True, verbose_name='Топы, купившие меньше, чем на 100$'),
        ),
        migrations.AddField(
            model_name='transaction',
            name='top_traders_bought_2500_5000',
            field=models.FloatField(blank=True, null=True, verbose_name='Топы, купившие на 2500$ - 5000$'),
        ),
        migrations.AddField(
            model_name='transaction',
            name='top_traders_bought_5000_more',
            field=models.FloatField(blank=True, null=True, verbose_name='Топы, купившие больше, чем на 5000$'),
        ),
        migrations.AddField(
            model_name='transaction',
            name='top_traders_bought_500_1000',
            field=models.FloatField(blank=True, null=True, verbose_name='Топы, купившие на 500$ - 1000$'),
        ),
        migrations.AddField(
            model_name='transaction',
            name='top_traders_no_bought',
            field=models.FloatField(blank=True, null=True, verbose_name='Топы без покупки'),
        ),
        migrations.AddField(
            model_name='transaction',
            name='top_traders_no_sold',
            field=models.FloatField(blank=True, null=True, verbose_name='Топы без продажи'),
        ),
        migrations.AddField(
            model_name='transaction',
            name='top_traders_pnl_1000_2500',
            field=models.FloatField(blank=True, null=True, verbose_name='Топы с PNL 1000$ - 2500$'),
        ),
        migrations.AddField(
            model_name='transaction',
            name='top_traders_pnl_100_500',
            field=models.FloatField(blank=True, null=True, verbose_name='Топы с PNL 100$ - 500$'),
        ),
        migrations.AddField(
            model_name='transaction',
            name='top_traders_pnl_100_less',
            field=models.FloatField(blank=True, null=True, verbose_name='Топы с PNL меньше, чем на 100$'),
        ),
        migrations.AddField(
            model_name='transaction',
            name='top_traders_pnl_2500_5000',
            field=models.FloatField(blank=True, null=True, verbose_name='Топы с PNL 2500$ - 5000$'),
        ),
        migrations.AddField(
            model_name='transaction',
            name='top_traders_pnl_5000_more',
            field=models.FloatField(blank=True, null=True, verbose_name='Топы с PNL больше, чем 5000$'),
        ),
        migrations.AddField(
            model_name='transaction',
            name='top_traders_pnl_500_1000',
            field=models.FloatField(blank=True, null=True, verbose_name='Топы с PNL 500$ - 1000$'),
        ),
        migrations.AddField(
            model_name='transaction',
            name='top_traders_pnl_loss',
            field=models.FloatField(blank=True, null=True, verbose_name='Топы с отрицательным PNL'),
        ),
        migrations.AddField(
            model_name='transaction',
            name='top_traders_pnl_profit',
            field=models.FloatField(blank=True, null=True, verbose_name='Топы с положительным PNL'),
        ),
        migrations.AddField(
            model_name='transaction',
            name='top_traders_sold_1000_2500',
            field=models.FloatField(blank=True, null=True, verbose_name='Топы, продавшие на 1000$ - 2500$'),
        ),
        migrations.AddField(
            model_name='transaction',
            name='top_traders_sold_100_500',
            field=models.FloatField(blank=True, null=True, verbose_name='Топы, продавшие на 100$ - 500$'),
        ),
        migrations.AddField(
            model_name='transaction',
            name='top_traders_sold_100_less',
            field=models.FloatField(blank=True, null=True, verbose_name='Топы, продавшие меньше, чем на 100$'),
        ),
        migrations.AddField(
            model_name='transaction',
            name='top_traders_sold_2500_5000',
            field=models.FloatField(blank=True, null=True, verbose_name='Топы, продавшие на 2500$ - 5000$'),
        ),
        migrations.AddField(
            model_name='transaction',
            name='top_traders_sold_5000_more',
            field=models.FloatField(blank=True, null=True, verbose_name='Топы, продавшие больше, чем на 5000$'),
        ),
        migrations.AddField(
            model_name='transaction',
            name='top_traders_sold_500_1000',
            field=models.FloatField(blank=True, null=True, verbose_name='Топы, продавшие на 500$ - 1000$'),
        ),
        migrations.AlterField(
            model_name='toptrader',
            name='chain',
            field=models.CharField(default='Solana', max_length=256, verbose_name='Сеть'),
        ),
        migrations.AlterField(
            model_name='toptrader',
            name='pair',
            field=models.CharField(max_length=256, verbose_name='Пара'),
        ),
    ]
