# Generated by Django 5.1 on 2024-10-12 20:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('token_hunter', '0004_transaction_snipers_bought_01_less_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='transaction',
            name='snipers_bought',
            field=models.CharField(blank=True, max_length=2048, null=True, verbose_name='Покупки снайперов'),
        ),
        migrations.AddField(
            model_name='transaction',
            name='snipers_sold',
            field=models.CharField(blank=True, max_length=2048, null=True, verbose_name='Продажи снайперов'),
        ),
        migrations.AddField(
            model_name='transaction',
            name='tt_bought',
            field=models.CharField(blank=True, max_length=2048, null=True, verbose_name='Покупки топов'),
        ),
        migrations.AddField(
            model_name='transaction',
            name='tt_sold',
            field=models.CharField(blank=True, max_length=2048, null=True, verbose_name='Продажи топов'),
        ),
    ]
