# Generated by Django 5.1 on 2024-11-18 10:01

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('token_hunter', '0006_rename_buying_buys_h1_transaction_buys_h1_b_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='transaction',
            name='buys_h1_s',
        ),
        migrations.RemoveField(
            model_name='transaction',
            name='buys_h24_s',
        ),
        migrations.RemoveField(
            model_name='transaction',
            name='buys_h6_s',
        ),
        migrations.RemoveField(
            model_name='transaction',
            name='buys_m5_s',
        ),
        migrations.RemoveField(
            model_name='transaction',
            name='fdv_s',
        ),
        migrations.RemoveField(
            model_name='transaction',
            name='liquidity_s',
        ),
        migrations.RemoveField(
            model_name='transaction',
            name='market_cap_s',
        ),
        migrations.RemoveField(
            model_name='transaction',
            name='price_change_h1_s',
        ),
        migrations.RemoveField(
            model_name='transaction',
            name='price_change_h24_s',
        ),
        migrations.RemoveField(
            model_name='transaction',
            name='price_change_h6_s',
        ),
        migrations.RemoveField(
            model_name='transaction',
            name='price_change_m5_s',
        ),
        migrations.RemoveField(
            model_name='transaction',
            name='sells_h1_s',
        ),
        migrations.RemoveField(
            model_name='transaction',
            name='sells_h24_s',
        ),
        migrations.RemoveField(
            model_name='transaction',
            name='sells_h6_s',
        ),
        migrations.RemoveField(
            model_name='transaction',
            name='sells_m5_s',
        ),
        migrations.RemoveField(
            model_name='transaction',
            name='volume_h1_s',
        ),
        migrations.RemoveField(
            model_name='transaction',
            name='volume_h24_s',
        ),
        migrations.RemoveField(
            model_name='transaction',
            name='volume_h6_s',
        ),
        migrations.RemoveField(
            model_name='transaction',
            name='volume_m5_s',
        ),
    ]
