# Generated by Django 5.1 on 2024-11-18 19:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('token_hunter', '0009_rename_transfers_b_transaction_transfers'),
    ]

    operations = [
        migrations.AlterField(
            model_name='settings',
            name='filter',
            field=models.CharField(blank=True, default='?rankBy=trendingScoreH6&order=desc&minLiq=1000&maxAge=1', max_length=1024, null=True, verbose_name='Фильтр по умолчанию'),
        ),
    ]
