# Generated by Django 5.1 on 2024-11-19 18:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('token_hunter', '0010_alter_settings_filter'),
    ]

    operations = [
        migrations.AddField(
            model_name='transaction',
            name='is_telegram_error',
            field=models.BooleanField(blank=True, default=False, null=True, verbose_name='Телеграм указан, но не существует'),
        ),
        migrations.AddField(
            model_name='transaction',
            name='is_twitter_error',
            field=models.BooleanField(blank=True, default=False, null=True, verbose_name='Твиттер указан, но не существует'),
        ),
        migrations.AddField(
            model_name='transaction',
            name='telegram_days',
            field=models.IntegerField(blank=True, null=True, verbose_name='Возраст первого чата Телеграм (дни)'),
        ),
        migrations.AddField(
            model_name='transaction',
            name='telegram_is_scam',
            field=models.BooleanField(blank=True, default=False, null=True, verbose_name='Наличие в Телеграм отметки о скаме'),
        ),
        migrations.AddField(
            model_name='transaction',
            name='telegram_members',
            field=models.IntegerField(blank=True, null=True, verbose_name='Количество подписчиков в Телеграме'),
        ),
        migrations.AddField(
            model_name='transaction',
            name='twitter_days',
            field=models.IntegerField(blank=True, null=True, verbose_name='Возраст Твиттера (дни)'),
        ),
        migrations.AddField(
            model_name='transaction',
            name='twitter_followers',
            field=models.IntegerField(blank=True, null=True, verbose_name='Количество подписчиков в Твиттере'),
        ),
        migrations.AddField(
            model_name='transaction',
            name='twitter_smart_followers',
            field=models.IntegerField(blank=True, null=True, verbose_name='Количество известных подписчиков в Твиттере'),
        ),
        migrations.AddField(
            model_name='transaction',
            name='twitter_tweets',
            field=models.IntegerField(blank=True, null=True, verbose_name='Количество постов в Твиттере'),
        ),
    ]
