# Generated by Django 5.1 on 2024-12-07 21:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('token_hunter', '0012_remove_transaction_telegram_days_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='BoostedTransactions',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('pair', models.CharField(max_length=256, verbose_name='Pair')),
                ('token_name', models.CharField(max_length=256, verbose_name='Имя токена')),
                ('token_address', models.CharField(max_length=256, verbose_name='Адрес токена')),
                ('price_b', models.FloatField(verbose_name='Цена покупки')),
                ('price_s', models.FloatField(blank=True, null=True, verbose_name='Цена продажи')),
                ('token_age_b', models.FloatField(verbose_name='Возраст на момент покупки')),
                ('token_age_s', models.FloatField(blank=True, null=True, verbose_name='Возраст на момент продажи')),
                ('transfers', models.IntegerField(blank=True, null=True, verbose_name='Количество трансферов')),
                ('transactions', models.IntegerField(blank=True, null=True, verbose_name='Количество транзакций')),
                ('buys_m5', models.IntegerField(blank=True, null=True, verbose_name='Количество покупок (5 минут)')),
                ('sells_m5', models.IntegerField(blank=True, null=True, verbose_name='Количество продаж (5 минут)')),
                ('buys_h1', models.IntegerField(blank=True, null=True, verbose_name='Количество покупок (1 час)')),
                ('sells_h1', models.IntegerField(blank=True, null=True, verbose_name='Количество продаж (1 час)')),
                ('buys_h6', models.IntegerField(blank=True, null=True, verbose_name='Количество покупок (6 часов)')),
                ('sells_h6', models.IntegerField(blank=True, null=True, verbose_name='Количество продаж (6 часов)')),
                ('buys_h24', models.IntegerField(blank=True, null=True, verbose_name='Количество покупок (24 часа)')),
                ('sells_h24', models.IntegerField(blank=True, null=True, verbose_name='Количество продаж (24 часа)')),
                ('volume_m5', models.FloatField(blank=True, null=True, verbose_name='Объём торгов (5 минут)')),
                ('volume_h1', models.FloatField(blank=True, null=True, verbose_name='Объём торгов (1 час)')),
                ('volume_h6', models.FloatField(blank=True, null=True, verbose_name='Объём торгов (6 часов)')),
                ('volume_h24', models.FloatField(blank=True, null=True, verbose_name='Объём торгов (24 часа)')),
                ('price_change_m5', models.FloatField(blank=True, null=True, verbose_name='Изменение цены (5 минут)')),
                ('price_change_h1', models.FloatField(blank=True, null=True, verbose_name='Изменение цены (1 час)')),
                ('price_change_h6', models.FloatField(blank=True, null=True, verbose_name='Изменение цены (6 часов)')),
                ('price_change_h24', models.FloatField(blank=True, null=True, verbose_name='Изменение цены (24 часа)')),
                ('liquidity', models.FloatField(blank=True, null=True, verbose_name='Ликвидность (5 минут)')),
                ('fdv', models.FloatField(blank=True, null=True, verbose_name='FDV')),
                ('market_cap', models.FloatField(blank=True, null=True, verbose_name='Рыночная капитализация')),
                ('is_mutable_metadata', models.BooleanField(blank=True, default=True, null=True, verbose_name='Изменяемые метаданные')),
                ('is_telegram', models.BooleanField(default=False, verbose_name='Наличие Телеграма')),
                ('is_twitter', models.BooleanField(default=False, verbose_name='Наличие Твиттера')),
                ('is_website', models.BooleanField(default=False, verbose_name='Наличие сайта')),
                ('boosts', models.IntegerField(blank=True, default=0, null=True, verbose_name='Буст')),
                ('telegram_members', models.IntegerField(blank=True, null=True, verbose_name='Количество подписчиков в Телеграме')),
                ('is_telegram_error', models.BooleanField(blank=True, default=False, null=True, verbose_name='Телеграм указан, но не существует')),
                ('twitter_days', models.IntegerField(blank=True, null=True, verbose_name='Возраст Твиттера (дни)')),
                ('twitter_tweets', models.IntegerField(blank=True, null=True, verbose_name='Количество постов в Твиттере')),
                ('twitter_followers', models.IntegerField(blank=True, null=True, verbose_name='Количество подписчиков в Твиттере')),
                ('twitter_smart_followers', models.IntegerField(blank=True, null=True, verbose_name='Количество известных подписчиков в Твиттере')),
                ('is_twitter_error', models.BooleanField(blank=True, default=False, null=True, verbose_name='Твиттер указан, но не существует')),
                ('opening_date', models.DateTimeField(auto_now_add=True, verbose_name='Время покупки')),
                ('closing_date', models.DateTimeField(blank=True, null=True, verbose_name='Время продажи')),
                ('PNL', models.DecimalField(blank=True, decimal_places=2, max_digits=12, null=True, verbose_name='PNL')),
                ('PNL_20', models.BooleanField(blank=True, null=True, verbose_name='PNL 20 %')),
                ('PNL_30', models.BooleanField(blank=True, null=True, verbose_name='PNL 30 %')),
                ('PNL_40', models.BooleanField(blank=True, null=True, verbose_name='PNL 40 %')),
                ('PNL_50', models.BooleanField(blank=True, null=True, verbose_name='PNL 50 %')),
                ('status', models.CharField(choices=[('open', 'Открытая'), ('closed', 'Закрытая')], default='open', max_length=64, verbose_name='Статус')),
                ('mode', models.CharField(choices=[('data_collection', 'Сбор данных'), ('emulation', 'Эмуляция'), ('real', 'Реальная покупка')], default='data_collection', max_length=64, verbose_name='Тип')),
            ],
            options={
                'verbose_name': 'Транзакция',
                'verbose_name_plural': 'Транзакции',
            },
        ),
        migrations.AddField(
            model_name='transaction',
            name='PNL_20',
            field=models.BooleanField(blank=True, null=True, verbose_name='PNL 20 %'),
        ),
        migrations.AddField(
            model_name='transaction',
            name='PNL_30',
            field=models.BooleanField(blank=True, null=True, verbose_name='PNL 30 %'),
        ),
        migrations.AddField(
            model_name='transaction',
            name='PNL_40',
            field=models.BooleanField(blank=True, null=True, verbose_name='PNL 40 %'),
        ),
        migrations.AddField(
            model_name='transaction',
            name='PNL_50',
            field=models.BooleanField(blank=True, null=True, verbose_name='PNL 50 %'),
        ),
    ]
