# Generated by Django 5.1 on 2024-12-08 19:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('token_hunter', '0013_boostedtransactions_transaction_pnl_20_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='boostedtransactions',
            name='PNL_10',
            field=models.BooleanField(blank=True, null=True, verbose_name='PNL 10 %'),
        ),
    ]
