# Generated by Django 5.1 on 2024-12-08 20:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('token_hunter', '0014_boostedtransactions_pnl_10'),
    ]

    operations = [
        migrations.DeleteModel(
            name='BoostedTransactions',
        ),
        migrations.RemoveField(
            model_name='transaction',
            name='transactions',
        ),
        migrations.AddField(
            model_name='transaction',
            name='PNL_10',
            field=models.BooleanField(blank=True, null=True, verbose_name='PNL 10 %'),
        ),
        migrations.AlterField(
            model_name='settings',
            name='mode',
            field=models.CharField(choices=[('data_collection', 'Сбор данных'), ('emulation', 'Эмуляция'), ('boosted', 'Boosted'), ('real', 'Реальная покупка')], default='data_collection', max_length=64, verbose_name='Режим'),
        ),
        migrations.AlterField(
            model_name='transaction',
            name='mode',
            field=models.CharField(choices=[('data_collection', 'Сбор данных'), ('emulation', 'Эмуляция'), ('boosted', 'Boosted'), ('real', 'Реальная покупка')], default='data_collection', max_length=64, verbose_name='Тип'),
        ),
    ]
