# Generated by Django 5.1 on 2025-01-02 10:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('token_hunter', '0015_delete_boostedtransactions_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='transaction',
            name='price_change_check',
            field=models.FloatField(blank=True, null=True, verbose_name='Изменение цены'),
        ),
    ]
