# Generated by Django 5.1 on 2025-01-16 21:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('token_hunter', '0016_transaction_price_change_check'),
    ]

    operations = [
        migrations.AddField(
            model_name='transaction',
            name='PNL_loss_10',
            field=models.BooleanField(blank=True, null=True, verbose_name='PNL -10 %'),
        ),
    ]
