# Generated by Django 5.1 on 2025-01-24 22:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('token_hunter', '0019_rename_transactions_buys_h1_max_settings_buys_h1_max_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='settings',
            name='name',
            field=models.CharField(default='name', max_length=512, verbose_name='Название'),
            preserve_default=False,
        ),
    ]
