# Generated by Django 5.1 on 2025-01-28 21:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('token_hunter', '0021_alter_settings_options_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='settings',
            name='tt_pnl_loss_min',
            field=models.IntegerField(blank=True, null=True, verbose_name='Максимальное количество отрицательных PNL у топов'),
        ),
    ]
