# Generated by Django 5.1 on 2025-01-28 22:56

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('token_hunter', '0022_settings_tt_pnl_loss_min'),
    ]

    operations = [
        migrations.AddField(
            model_name='transaction',
            name='settings',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='token_hunter.settings', verbose_name='Настройки'),
        ),
        migrations.AlterField(
            model_name='settings',
            name='tt_bought_sum_min',
            field=models.FloatField(blank=True, null=True, verbose_name='Минимальная сумма покупок топов'),
        ),
    ]
