# Generated by Django 5.1 on 2025-02-06 01:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('token_hunter', '0024_settings_boost_max_settings_boost_min'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='transaction',
            name='PNL_loss_5',
        ),
        migrations.AddField(
            model_name='transaction',
            name='dextscore',
            field=models.IntegerField(blank=True, default=0, null=True, verbose_name='DextScore'),
        ),
    ]
