# Generated by Django 5.1 on 2025-02-06 20:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('token_hunter', '0025_remove_transaction_pnl_loss_5_transaction_dextscore'),
    ]

    operations = [
        migrations.AddField(
            model_name='transaction',
            name='PNL_100',
            field=models.BooleanField(blank=True, null=True, verbose_name='PNL 100 %'),
        ),
        migrations.AddField(
            model_name='transaction',
            name='PNL_200',
            field=models.BooleanField(blank=True, null=True, verbose_name='PNL 200 %'),
        ),
        migrations.AddField(
            model_name='transaction',
            name='tt_speed',
            field=models.CharField(blank=True, max_length=2048, null=True, verbose_name='Скорость топов'),
        ),
        migrations.AddField(
            model_name='transaction',
            name='tt_unrealized',
            field=models.CharField(blank=True, max_length=2048, null=True, verbose_name='Нереализованные токены топов'),
        ),
    ]
