# Generated by Django 5.1 on 2025-02-07 20:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('token_hunter', '0026_transaction_pnl_100_transaction_pnl_200_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='transaction',
            name='boosts_count',
            field=models.IntegerField(blank=True, default=0, null=True, verbose_name='Количество бустов'),
        ),
    ]
