# Generated by Django 5.1 on 2025-02-08 17:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('token_hunter', '0027_transaction_boosts_count'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='transaction',
            name='boosts_count',
        ),
        migrations.AddField(
            model_name='transaction',
            name='boosts_ages',
            field=models.CharField(blank=True, max_length=2048, null=True, verbose_name='Возраст на момент бустов'),
        ),
    ]
