# Generated by Django 5.1 on 2025-02-09 00:10

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('token_hunter', '0028_remove_transaction_boosts_count_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='settings',
            name='filter',
        ),
    ]
