# Generated by Django 5.1 on 2025-02-10 00:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('token_hunter', '0030_toptrader_transaction_count'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='settings',
            name='stop_loss',
        ),
        migrations.RemoveField(
            model_name='settings',
            name='take_profit',
        ),
        migrations.AlterField(
            model_name='toptrader',
            name='transaction_count',
            field=models.IntegerField(default=0, verbose_name='Количество транзакций'),
        ),
    ]
