# Generated by Django 5.1 on 2025-02-13 23:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('token_hunter', '0031_remove_settings_stop_loss_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='transaction',
            name='holders_liquidity',
            field=models.CharField(blank=True, max_length=2048, null=True, verbose_name='Процент токенов в ликвидности'),
        ),
        migrations.AddField(
            model_name='transaction',
            name='holders_percentages',
            field=models.CharField(blank=True, max_length=2048, null=True, verbose_name='Процент токенов у основных держателей'),
        ),
        migrations.AddField(
            model_name='transaction',
            name='holders_total',
            field=models.IntegerField(blank=True, null=True, verbose_name='Количество держателей'),
        ),
        migrations.AddField(
            model_name='transaction',
            name='sns_unrealized',
            field=models.CharField(blank=True, max_length=2048, null=True, verbose_name='Нереализованная сумма снайперов'),
        ),
        migrations.AlterField(
            model_name='transaction',
            name='tt_unrealized',
            field=models.CharField(blank=True, max_length=2048, null=True, verbose_name='Нереализованная сумма топов'),
        ),
    ]
