# Generated by Django 5.1 on 2025-03-08 20:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('token_hunter', '0032_transaction_holders_liquidity_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='transaction',
            name='PNL_100',
        ),
        migrations.RemoveField(
            model_name='transaction',
            name='PNL_200',
        ),
        migrations.RemoveField(
            model_name='transaction',
            name='PNL_loss_10',
        ),
        migrations.AddField(
            model_name='transaction',
            name='date',
            field=models.CharField(blank=True, max_length=16384, null=True, verbose_name='Даты транзакций'),
        ),
        migrations.AddField(
            model_name='transaction',
            name='operations',
            field=models.CharField(blank=True, max_length=16384, null=True, verbose_name='Операции'),
        ),
        migrations.AddField(
            model_name='transaction',
            name='prices',
            field=models.CharField(blank=True, max_length=16384, null=True, verbose_name='Изменение цены'),
        ),
        migrations.AddField(
            model_name='transaction',
            name='trades_for_maker',
            field=models.CharField(blank=True, max_length=16384, null=True, verbose_name='Количество транзакций для кошелька'),
        ),
        migrations.AddField(
            model_name='transaction',
            name='trades_makers',
            field=models.CharField(blank=True, max_length=16384, null=True, verbose_name='Торгующие кошельки'),
        ),
        migrations.AddField(
            model_name='transaction',
            name='trades_sum',
            field=models.CharField(blank=True, max_length=16384, null=True, verbose_name='Суммы операций'),
        ),
        migrations.AddField(
            model_name='transaction',
            name='transactions',
            field=models.IntegerField(blank=True, null=True, verbose_name='Общее количество транзакций'),
        ),
    ]
