# Generated by Django 5.1 on 2025-03-24 18:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('token_hunter', '0033_remove_transaction_pnl_100_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='settings',
            name='mode',
            field=models.CharField(choices=[('data_collection', 'Сбор данных'), ('emulation', 'Эмуляция'), ('boosted', 'Буст'), ('real', 'Реальная покупка')], default='boosted', max_length=64, verbose_name='Режим'),
        ),
        migrations.AlterField(
            model_name='settings',
            name='monitoring_rule',
            field=models.CharField(choices=[('boosted', 'Буст'), ('latest', 'Свежие'), ('filter', 'Фильтр')], default='boosted', max_length=64, verbose_name='Правильно мониторинга токенов'),
        ),
        migrations.AlterField(
            model_name='transaction',
            name='mode',
            field=models.CharField(choices=[('data_collection', 'Сбор данных'), ('emulation', 'Эмуляция'), ('boosted', 'Буст'), ('real', 'Реальная покупка')], default='data_collection', max_length=64, verbose_name='Тип'),
        ),
    ]
