# Generated by Django 5.1 on 2025-03-27 00:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('token_hunter', '0034_alter_settings_mode_alter_settings_monitoring_rule_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='transaction',
            name='monitoring_rule',
            field=models.CharField(choices=[('boosted', 'Буст'), ('latest', 'Свежие'), ('filter', 'Фильтр')], default='boosted', max_length=64, verbose_name='Тип'),
        ),
        migrations.AlterField(
            model_name='settings',
            name='mode',
            field=models.CharField(choices=[('data_collection', 'Сбор данных'), ('emulation', 'Эмуляция'), ('real', 'Реальная покупка')], default='emulation', max_length=64, verbose_name='Режим'),
        ),
        migrations.AlterField(
            model_name='transaction',
            name='mode',
            field=models.CharField(choices=[('data_collection', 'Сбор данных'), ('emulation', 'Эмуляция'), ('real', 'Реальная покупка')], default='data_collection', max_length=64, verbose_name='Тип'),
        ),
    ]
