# Generated by Django 5.1 on 2025-03-27 01:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('token_hunter', '0035_transaction_monitoring_rule_alter_settings_mode_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='settings',
            name='mode',
            field=models.CharField(choices=[('data_collection', 'Сбор данных'), ('emulation', 'Эмуляция'), ('real_buy', 'Реальная покупка')], default='emulation', max_length=64, verbose_name='Режим'),
        ),
        migrations.AlterField(
            model_name='transaction',
            name='mode',
            field=models.CharField(choices=[('data_collection', 'Сбор данных'), ('emulation', 'Эмуляция'), ('real_buy', 'Реальная покупка')], default='data_collection', max_length=64, verbose_name='Тип'),
        ),
    ]
