# Generated by Django 5.1 on 2025-03-27 15:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('token_hunter', '0036_alter_settings_mode_alter_transaction_mode'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='transaction',
            name='price_change_check',
        ),
        migrations.AlterField(
            model_name='transaction',
            name='mode',
            field=models.CharField(choices=[('data_collection', 'Сбор данных'), ('emulation', 'Эмуляция'), ('real_buy', 'Реальная покупка')], default='data_collection', max_length=64, verbose_name='Режим'),
        ),
    ]
