# Generated by Django 5.1 on 2025-03-27 22:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('token_hunter', '0037_remove_transaction_price_change_check_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='toptrader',
            name='PNL',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=12, null=True, verbose_name='PNL'),
        ),
    ]
