# Generated by Django 5.1 on 2025-03-28 14:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('token_hunter', '0038_alter_toptrader_pnl'),
    ]

    operations = [
        migrations.AlterField(
            model_name='transaction',
            name='PNL',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=12, null=True, verbose_name='PNL, %'),
        ),
        migrations.AlterField(
            model_name='transaction',
            name='boosts_ages',
            field=models.CharField(blank=True, max_length=2048, null=True, verbose_name='Возраст на момент бустов, мин.'),
        ),
        migrations.AlterField(
            model_name='transaction',
            name='fdv',
            field=models.FloatField(blank=True, null=True, verbose_name='FDV, USD'),
        ),
        migrations.AlterField(
            model_name='transaction',
            name='liquidity',
            field=models.FloatField(blank=True, null=True, verbose_name='Ликвидность (5 минут), %'),
        ),
        migrations.AlterField(
            model_name='transaction',
            name='market_cap',
            field=models.FloatField(blank=True, null=True, verbose_name='Рыночная капитализация, USD'),
        ),
        migrations.AlterField(
            model_name='transaction',
            name='price_b',
            field=models.FloatField(verbose_name='Цена покупки, USD'),
        ),
        migrations.AlterField(
            model_name='transaction',
            name='price_change_h1',
            field=models.FloatField(blank=True, null=True, verbose_name='Изменение цены (1 час), %'),
        ),
        migrations.AlterField(
            model_name='transaction',
            name='price_change_h24',
            field=models.FloatField(blank=True, null=True, verbose_name='Изменение цены (24 часа), %'),
        ),
        migrations.AlterField(
            model_name='transaction',
            name='price_change_h6',
            field=models.FloatField(blank=True, null=True, verbose_name='Изменение цены (6 часов), %'),
        ),
        migrations.AlterField(
            model_name='transaction',
            name='price_change_m5',
            field=models.FloatField(blank=True, null=True, verbose_name='Изменение цены (5 минут), %'),
        ),
        migrations.AlterField(
            model_name='transaction',
            name='price_s',
            field=models.FloatField(blank=True, null=True, verbose_name='Цена продажи, USD'),
        ),
        migrations.AlterField(
            model_name='transaction',
            name='token_age_b',
            field=models.FloatField(verbose_name='Возраст на момент покупки, мин.'),
        ),
        migrations.AlterField(
            model_name='transaction',
            name='token_age_s',
            field=models.FloatField(blank=True, null=True, verbose_name='Возраст на момент продажи, мин.'),
        ),
        migrations.AlterField(
            model_name='transaction',
            name='twitter_days',
            field=models.IntegerField(blank=True, null=True, verbose_name='Возраст Твиттера, день'),
        ),
        migrations.AlterField(
            model_name='transaction',
            name='volume_h1',
            field=models.FloatField(blank=True, null=True, verbose_name='Объём торгов (1 час), %'),
        ),
        migrations.AlterField(
            model_name='transaction',
            name='volume_h24',
            field=models.FloatField(blank=True, null=True, verbose_name='Объём торгов (24 часа), %'),
        ),
        migrations.AlterField(
            model_name='transaction',
            name='volume_h6',
            field=models.FloatField(blank=True, null=True, verbose_name='Объём торгов (6 часов), %'),
        ),
        migrations.AlterField(
            model_name='transaction',
            name='volume_m5',
            field=models.FloatField(blank=True, null=True, verbose_name='Объём торгов (5 минут), %'),
        ),
    ]
