# Generated by Django 5.1 on 2025-03-28 17:23

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('token_hunter', '0039_alter_transaction_pnl_alter_transaction_boosts_ages_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='transaction',
            name='transfers',
        ),
    ]
