# Generated by Django 5.1 on 2025-06-08 13:52

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('token_hunter', '0040_remove_transaction_transfers'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='settings',
            options={'ordering': ['name'], 'verbose_name': 'Settings', 'verbose_name_plural': 'Settings'},
        ),
        migrations.AlterModelOptions(
            name='toptrader',
            options={'verbose_name': 'Top Wallet', 'verbose_name_plural': 'Top Wallets'},
        ),
        migrations.AlterModelOptions(
            name='transaction',
            options={'verbose_name': 'Transaction', 'verbose_name_plural': 'Transactions'},
        ),
        migrations.RemoveField(
            model_name='settings',
            name='sns_bought_sum_max',
        ),
        migrations.RemoveField(
            model_name='settings',
            name='sns_bought_sum_min',
        ),
        migrations.RemoveField(
            model_name='settings',
            name='sns_held_all_max',
        ),
        migrations.RemoveField(
            model_name='settings',
            name='sns_held_all_min',
        ),
        migrations.RemoveField(
            model_name='settings',
            name='sns_no_bought_max',
        ),
        migrations.RemoveField(
            model_name='settings',
            name='sns_no_bought_min',
        ),
        migrations.RemoveField(
            model_name='settings',
            name='sns_no_sold_max',
        ),
        migrations.RemoveField(
            model_name='settings',
            name='sns_no_sold_min',
        ),
        migrations.RemoveField(
            model_name='settings',
            name='sns_pnl_loss_max',
        ),
        migrations.RemoveField(
            model_name='settings',
            name='sns_pnl_loss_min',
        ),
        migrations.RemoveField(
            model_name='settings',
            name='sns_sold_all_max',
        ),
        migrations.RemoveField(
            model_name='settings',
            name='sns_sold_all_min',
        ),
        migrations.RemoveField(
            model_name='settings',
            name='sns_sold_some_max',
        ),
        migrations.RemoveField(
            model_name='settings',
            name='sns_sold_some_min',
        ),
        migrations.RemoveField(
            model_name='settings',
            name='sns_sold_sum_max',
        ),
        migrations.RemoveField(
            model_name='settings',
            name='sns_sold_sum_min',
        ),
        migrations.RemoveField(
            model_name='transaction',
            name='sns_bought',
        ),
        migrations.RemoveField(
            model_name='transaction',
            name='sns_held_all',
        ),
        migrations.RemoveField(
            model_name='transaction',
            name='sns_sold',
        ),
        migrations.RemoveField(
            model_name='transaction',
            name='sns_sold_all',
        ),
        migrations.RemoveField(
            model_name='transaction',
            name='sns_sold_some',
        ),
        migrations.RemoveField(
            model_name='transaction',
            name='sns_unrealized',
        ),
        migrations.AlterField(
            model_name='settings',
            name='boost_max',
            field=models.IntegerField(blank=True, null=True, verbose_name='Maximum Boost'),
        ),
        migrations.AlterField(
            model_name='settings',
            name='boost_min',
            field=models.IntegerField(blank=True, null=True, verbose_name='Minimum Boost'),
        ),
        migrations.AlterField(
            model_name='settings',
            name='buys_h1_max',
            field=models.IntegerField(blank=True, null=True, verbose_name='Maximum Buys (1 hour)'),
        ),
        migrations.AlterField(
            model_name='settings',
            name='buys_h1_min',
            field=models.IntegerField(blank=True, null=True, verbose_name='Minimum Buys (1 hour)'),
        ),
        migrations.AlterField(
            model_name='settings',
            name='buys_h24_max',
            field=models.IntegerField(blank=True, null=True, verbose_name='Maximum Buys (24 hours)'),
        ),
        migrations.AlterField(
            model_name='settings',
            name='buys_h24_min',
            field=models.IntegerField(blank=True, null=True, verbose_name='Minimum Buys (24 hours)'),
        ),
        migrations.AlterField(
            model_name='settings',
            name='buys_h6_max',
            field=models.IntegerField(blank=True, null=True, verbose_name='Maximum Buys (6 hours)'),
        ),
        migrations.AlterField(
            model_name='settings',
            name='buys_h6_min',
            field=models.IntegerField(blank=True, null=True, verbose_name='Minimum Buys (6 hours)'),
        ),
        migrations.AlterField(
            model_name='settings',
            name='buys_m5_max',
            field=models.IntegerField(blank=True, null=True, verbose_name='Maximum Buys (5 minutes)'),
        ),
        migrations.AlterField(
            model_name='settings',
            name='buys_m5_min',
            field=models.IntegerField(blank=True, null=True, verbose_name='Minimum Buys (5 minutes)'),
        ),
        migrations.AlterField(
            model_name='settings',
            name='fdv_max',
            field=models.FloatField(blank=True, null=True, verbose_name='Maximum FDV'),
        ),
        migrations.AlterField(
            model_name='settings',
            name='fdv_min',
            field=models.FloatField(blank=True, null=True, verbose_name='Minimum FDV'),
        ),
        migrations.AlterField(
            model_name='settings',
            name='is_socio',
            field=models.BooleanField(default=False, verbose_name='Presence of at least one social network or website'),
        ),
        migrations.AlterField(
            model_name='settings',
            name='is_telegram',
            field=models.BooleanField(default=False, verbose_name='Has Telegram'),
        ),
        migrations.AlterField(
            model_name='settings',
            name='is_twitter',
            field=models.BooleanField(default=False, verbose_name='Has Twitter'),
        ),
        migrations.AlterField(
            model_name='settings',
            name='is_website',
            field=models.BooleanField(default=False, verbose_name='Has Website'),
        ),
        migrations.AlterField(
            model_name='settings',
            name='liquidity_max',
            field=models.FloatField(blank=True, null=True, verbose_name='Maximum Liquidity'),
        ),
        migrations.AlterField(
            model_name='settings',
            name='liquidity_min',
            field=models.FloatField(blank=True, default=1000, null=True, verbose_name='Minimum Liquidity'),
        ),
        migrations.AlterField(
            model_name='settings',
            name='market_cap_max',
            field=models.FloatField(blank=True, null=True, verbose_name='Maximum Market Cap'),
        ),
        migrations.AlterField(
            model_name='settings',
            name='market_cap_min',
            field=models.FloatField(blank=True, null=True, verbose_name='Minimum Market Cap'),
        ),
        migrations.AlterField(
            model_name='settings',
            name='mode',
            field=models.CharField(choices=[('data_collection', 'Data Collection'), ('simulation', 'Simulation'), ('real_buy', 'Real Buy')], default='simulation', max_length=64, verbose_name='Mode'),
        ),
        migrations.AlterField(
            model_name='settings',
            name='monitoring_rule',
            field=models.CharField(choices=[('boosted', 'Boosted'), ('latest', 'Latest'), ('filter', 'Filter')], default='boosted', max_length=64, verbose_name='Token Monitoring Rule'),
        ),
        migrations.AlterField(
            model_name='settings',
            name='name',
            field=models.CharField(max_length=512, verbose_name='Name'),
        ),
        migrations.AlterField(
            model_name='settings',
            name='price_change_h1_max',
            field=models.FloatField(blank=True, null=True, verbose_name='Maximum Price Change (1 hour)'),
        ),
        migrations.AlterField(
            model_name='settings',
            name='price_change_h1_min',
            field=models.FloatField(blank=True, null=True, verbose_name='Minimum Price Change (1 hour)'),
        ),
        migrations.AlterField(
            model_name='settings',
            name='price_change_h24_max',
            field=models.FloatField(blank=True, null=True, verbose_name='Maximum Price Change (24 hours)'),
        ),
        migrations.AlterField(
            model_name='settings',
            name='price_change_h24_min',
            field=models.FloatField(blank=True, null=True, verbose_name='Minimum Price Change (24 hours)'),
        ),
        migrations.AlterField(
            model_name='settings',
            name='price_change_h6_max',
            field=models.FloatField(blank=True, null=True, verbose_name='Maximum Price Change (6 hours)'),
        ),
        migrations.AlterField(
            model_name='settings',
            name='price_change_h6_min',
            field=models.FloatField(blank=True, null=True, verbose_name='Minimum Price Change (6 hours)'),
        ),
        migrations.AlterField(
            model_name='settings',
            name='price_change_m5_max',
            field=models.FloatField(blank=True, null=True, verbose_name='Maximum Price Change (5 minutes)'),
        ),
        migrations.AlterField(
            model_name='settings',
            name='price_change_m5_min',
            field=models.FloatField(blank=True, null=True, verbose_name='Minimum Price Change (5 minutes)'),
        ),
        migrations.AlterField(
            model_name='settings',
            name='price_max',
            field=models.FloatField(blank=True, null=True, verbose_name='Maximum Price'),
        ),
        migrations.AlterField(
            model_name='settings',
            name='price_min',
            field=models.FloatField(blank=True, null=True, verbose_name='Minimum Price'),
        ),
        migrations.AlterField(
            model_name='settings',
            name='sells_h1_max',
            field=models.IntegerField(blank=True, null=True, verbose_name='Maximum Sells (1 hour)'),
        ),
        migrations.AlterField(
            model_name='settings',
            name='sells_h1_min',
            field=models.IntegerField(blank=True, null=True, verbose_name='Minimum Sells (1 hour)'),
        ),
        migrations.AlterField(
            model_name='settings',
            name='sells_h24_max',
            field=models.IntegerField(blank=True, null=True, verbose_name='Maximum Sells (24 hours)'),
        ),
        migrations.AlterField(
            model_name='settings',
            name='sells_h24_min',
            field=models.IntegerField(blank=True, null=True, verbose_name='Minimum Sells (24 hours)'),
        ),
        migrations.AlterField(
            model_name='settings',
            name='sells_h6_max',
            field=models.IntegerField(blank=True, null=True, verbose_name='Maximum Sells (6 hours)'),
        ),
        migrations.AlterField(
            model_name='settings',
            name='sells_h6_min',
            field=models.IntegerField(blank=True, null=True, verbose_name='Minimum Sells (6 hours)'),
        ),
        migrations.AlterField(
            model_name='settings',
            name='sells_m5_max',
            field=models.IntegerField(blank=True, null=True, verbose_name='Maximum Sells (5 minutes)'),
        ),
        migrations.AlterField(
            model_name='settings',
            name='sells_m5_min',
            field=models.IntegerField(blank=True, null=True, verbose_name='Minimum Sells (5 minutes)'),
        ),
        migrations.AlterField(
            model_name='settings',
            name='token_age_max',
            field=models.FloatField(blank=True, default=5, null=True, verbose_name='Maximum Age'),
        ),
        migrations.AlterField(
            model_name='settings',
            name='token_age_min',
            field=models.FloatField(blank=True, null=True, verbose_name='Minimum Age'),
        ),
        migrations.AlterField(
            model_name='settings',
            name='tt_bought_sum_max',
            field=models.FloatField(blank=True, null=True, verbose_name='Maximum Top Trader Buy Sum'),
        ),
        migrations.AlterField(
            model_name='settings',
            name='tt_bought_sum_min',
            field=models.FloatField(blank=True, null=True, verbose_name='Minimum Top Trader Buy Sum'),
        ),
        migrations.AlterField(
            model_name='settings',
            name='tt_no_bought_max',
            field=models.IntegerField(blank=True, null=True, verbose_name='Maximum Top Traders Without Buys'),
        ),
        migrations.AlterField(
            model_name='settings',
            name='tt_no_bought_min',
            field=models.IntegerField(blank=True, null=True, verbose_name='Minimum Top Traders Without Buys'),
        ),
        migrations.AlterField(
            model_name='settings',
            name='tt_no_sold_max',
            field=models.IntegerField(blank=True, null=True, verbose_name='Maximum Top Traders Without Sells'),
        ),
        migrations.AlterField(
            model_name='settings',
            name='tt_no_sold_min',
            field=models.IntegerField(blank=True, null=True, verbose_name='Minimum Top Traders Without Sells'),
        ),
        migrations.AlterField(
            model_name='settings',
            name='tt_pnl_loss_max',
            field=models.IntegerField(blank=True, null=True, verbose_name='Maximum Top Traders with Negative PNL'),
        ),
        migrations.AlterField(
            model_name='settings',
            name='tt_pnl_loss_min',
            field=models.IntegerField(blank=True, null=True, verbose_name='Maximum Top Traders with Negative PNL'),
        ),
        migrations.AlterField(
            model_name='settings',
            name='tt_sold_sum_max',
            field=models.FloatField(blank=True, null=True, verbose_name='Maximum Top Trader Sell Sum'),
        ),
        migrations.AlterField(
            model_name='settings',
            name='tt_sold_sum_min',
            field=models.FloatField(blank=True, null=True, verbose_name='Maximum Top Trader Sell Sum'),
        ),
        migrations.AlterField(
            model_name='settings',
            name='volume_h1_max',
            field=models.FloatField(blank=True, null=True, verbose_name='Maximum Trading Volume (1 hour)'),
        ),
        migrations.AlterField(
            model_name='settings',
            name='volume_h1_min',
            field=models.FloatField(blank=True, null=True, verbose_name='Minimum Trading Volume (1 hour)'),
        ),
        migrations.AlterField(
            model_name='settings',
            name='volume_h24_max',
            field=models.FloatField(blank=True, null=True, verbose_name='Maximum Trading Volume (24 hours)'),
        ),
        migrations.AlterField(
            model_name='settings',
            name='volume_h24_min',
            field=models.FloatField(blank=True, null=True, verbose_name='Minimum Trading Volume (24 hours)'),
        ),
        migrations.AlterField(
            model_name='settings',
            name='volume_h6_max',
            field=models.FloatField(blank=True, null=True, verbose_name='Maximum Trading Volume (6 hours)'),
        ),
        migrations.AlterField(
            model_name='settings',
            name='volume_h6_min',
            field=models.FloatField(blank=True, null=True, verbose_name='Minimum Trading Volume (6 hours)'),
        ),
        migrations.AlterField(
            model_name='settings',
            name='volume_m5_max',
            field=models.FloatField(blank=True, null=True, verbose_name='Maximum Trading Volume (5 minutes)'),
        ),
        migrations.AlterField(
            model_name='settings',
            name='volume_m5_min',
            field=models.FloatField(blank=True, null=True, verbose_name='Minimum Trading Volume (5 minutes)'),
        ),
        migrations.AlterField(
            model_name='toptrader',
            name='bought',
            field=models.IntegerField(verbose_name='Bought'),
        ),
        migrations.AlterField(
            model_name='toptrader',
            name='chain',
            field=models.CharField(default='Solana', max_length=256, verbose_name='Chain'),
        ),
        migrations.AlterField(
            model_name='toptrader',
            name='created_date',
            field=models.DateTimeField(auto_now_add=True, verbose_name='Created Date'),
        ),
        migrations.AlterField(
            model_name='toptrader',
            name='pair',
            field=models.CharField(max_length=256, verbose_name='Pair'),
        ),
        migrations.AlterField(
            model_name='toptrader',
            name='sold',
            field=models.IntegerField(verbose_name='Sold'),
        ),
        migrations.AlterField(
            model_name='toptrader',
            name='token_address',
            field=models.CharField(max_length=256, verbose_name='Token Address'),
        ),
        migrations.AlterField(
            model_name='toptrader',
            name='token_name',
            field=models.CharField(max_length=256, verbose_name='Token Name'),
        ),
        migrations.AlterField(
            model_name='toptrader',
            name='transaction_count',
            field=models.IntegerField(default=0, verbose_name='Transaction Count'),
        ),
        migrations.AlterField(
            model_name='toptrader',
            name='wallet_address',
            field=models.CharField(max_length=256, verbose_name='Wallet Address'),
        ),
        migrations.AlterField(
            model_name='transaction',
            name='boosts',
            field=models.IntegerField(blank=True, default=0, null=True, verbose_name='Boosts'),
        ),
        migrations.AlterField(
            model_name='transaction',
            name='boosts_ages',
            field=models.CharField(blank=True, max_length=2048, null=True, verbose_name='Age at Boosts, min.'),
        ),
        migrations.AlterField(
            model_name='transaction',
            name='buys_h1',
            field=models.IntegerField(blank=True, null=True, verbose_name='Buys (1 hour)'),
        ),
        migrations.AlterField(
            model_name='transaction',
            name='buys_h24',
            field=models.IntegerField(blank=True, null=True, verbose_name='Buys (24 hours)'),
        ),
        migrations.AlterField(
            model_name='transaction',
            name='buys_h6',
            field=models.IntegerField(blank=True, null=True, verbose_name='Buys (6 hours)'),
        ),
        migrations.AlterField(
            model_name='transaction',
            name='buys_m5',
            field=models.IntegerField(blank=True, null=True, verbose_name='Buys (5 minutes)'),
        ),
        migrations.AlterField(
            model_name='transaction',
            name='closing_date',
            field=models.DateTimeField(blank=True, null=True, verbose_name='Closing Date'),
        ),
        migrations.AlterField(
            model_name='transaction',
            name='date',
            field=models.CharField(blank=True, max_length=16384, null=True, verbose_name='Transaction Dates'),
        ),
        migrations.AlterField(
            model_name='transaction',
            name='holders_liquidity',
            field=models.CharField(blank=True, max_length=2048, null=True, verbose_name='Percentage of Tokens in Liquidity'),
        ),
        migrations.AlterField(
            model_name='transaction',
            name='holders_percentages',
            field=models.CharField(blank=True, max_length=2048, null=True, verbose_name='Percentage of Tokens Held by Main Holders'),
        ),
        migrations.AlterField(
            model_name='transaction',
            name='holders_total',
            field=models.IntegerField(blank=True, null=True, verbose_name='Total Holders'),
        ),
        migrations.AlterField(
            model_name='transaction',
            name='is_mutable_metadata',
            field=models.BooleanField(blank=True, default=True, null=True, verbose_name='Mutable Metadata'),
        ),
        migrations.AlterField(
            model_name='transaction',
            name='is_telegram',
            field=models.BooleanField(default=False, verbose_name='Has Telegram'),
        ),
        migrations.AlterField(
            model_name='transaction',
            name='is_telegram_error',
            field=models.BooleanField(blank=True, default=False, null=True, verbose_name='Telegram provided but does not exist'),
        ),
        migrations.AlterField(
            model_name='transaction',
            name='is_twitter',
            field=models.BooleanField(default=False, verbose_name='Has Twitter'),
        ),
        migrations.AlterField(
            model_name='transaction',
            name='is_twitter_error',
            field=models.BooleanField(blank=True, default=False, null=True, verbose_name='Twitter provided but does not exist'),
        ),
        migrations.AlterField(
            model_name='transaction',
            name='is_website',
            field=models.BooleanField(default=False, verbose_name='Has Website'),
        ),
        migrations.AlterField(
            model_name='transaction',
            name='liquidity',
            field=models.FloatField(blank=True, null=True, verbose_name='Liquidity (5 minutes), %'),
        ),
        migrations.AlterField(
            model_name='transaction',
            name='market_cap',
            field=models.FloatField(blank=True, null=True, verbose_name='Market Cap, USD'),
        ),
        migrations.AlterField(
            model_name='transaction',
            name='mode',
            field=models.CharField(choices=[('data_collection', 'Data Collection'), ('simulation', 'Simulation'), ('real_buy', 'Real Buy')], default='data_collection', max_length=64, verbose_name='Mode'),
        ),
        migrations.AlterField(
            model_name='transaction',
            name='monitoring_rule',
            field=models.CharField(choices=[('boosted', 'Boosted'), ('latest', 'Latest'), ('filter', 'Filter')], default='boosted', max_length=64, verbose_name='Type'),
        ),
        migrations.AlterField(
            model_name='transaction',
            name='opening_date',
            field=models.DateTimeField(auto_now_add=True, verbose_name='Created Date'),
        ),
        migrations.AlterField(
            model_name='transaction',
            name='operations',
            field=models.CharField(blank=True, max_length=16384, null=True, verbose_name='Operations'),
        ),
        migrations.AlterField(
            model_name='transaction',
            name='price_b',
            field=models.FloatField(verbose_name='Buying Price, USD'),
        ),
        migrations.AlterField(
            model_name='transaction',
            name='price_change_h1',
            field=models.FloatField(blank=True, null=True, verbose_name='Price Change (1 hour), %'),
        ),
        migrations.AlterField(
            model_name='transaction',
            name='price_change_h24',
            field=models.FloatField(blank=True, null=True, verbose_name='Price Change (24 hours), %'),
        ),
        migrations.AlterField(
            model_name='transaction',
            name='price_change_h6',
            field=models.FloatField(blank=True, null=True, verbose_name='Price Change (6 hours), %'),
        ),
        migrations.AlterField(
            model_name='transaction',
            name='price_change_m5',
            field=models.FloatField(blank=True, null=True, verbose_name='Price Change (5 minutes), %'),
        ),
        migrations.AlterField(
            model_name='transaction',
            name='price_s',
            field=models.FloatField(blank=True, null=True, verbose_name='Selling Price, USD'),
        ),
        migrations.AlterField(
            model_name='transaction',
            name='prices',
            field=models.CharField(blank=True, max_length=16384, null=True, verbose_name='Price Change'),
        ),
        migrations.AlterField(
            model_name='transaction',
            name='sells_h1',
            field=models.IntegerField(blank=True, null=True, verbose_name='Sells (1 hour)'),
        ),
        migrations.AlterField(
            model_name='transaction',
            name='sells_h24',
            field=models.IntegerField(blank=True, null=True, verbose_name='Sells (24 hours)'),
        ),
        migrations.AlterField(
            model_name='transaction',
            name='sells_h6',
            field=models.IntegerField(blank=True, null=True, verbose_name='Sells (6 hours)'),
        ),
        migrations.AlterField(
            model_name='transaction',
            name='sells_m5',
            field=models.IntegerField(blank=True, null=True, verbose_name='Sells (5 minutes)'),
        ),
        migrations.AlterField(
            model_name='transaction',
            name='settings',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='token_hunter.settings', verbose_name='Settings'),
        ),
        migrations.AlterField(
            model_name='transaction',
            name='status',
            field=models.CharField(choices=[('open', 'Open'), ('closed', 'Closed')], default='open', max_length=64, verbose_name='Status'),
        ),
        migrations.AlterField(
            model_name='transaction',
            name='telegram_members',
            field=models.IntegerField(blank=True, null=True, verbose_name='Telegram Members'),
        ),
        migrations.AlterField(
            model_name='transaction',
            name='token_address',
            field=models.CharField(max_length=256, verbose_name='Token Address'),
        ),
        migrations.AlterField(
            model_name='transaction',
            name='token_age_b',
            field=models.FloatField(verbose_name='Age at Buy, min.'),
        ),
        migrations.AlterField(
            model_name='transaction',
            name='token_age_s',
            field=models.FloatField(blank=True, null=True, verbose_name='Age at Sell, min.'),
        ),
        migrations.AlterField(
            model_name='transaction',
            name='token_name',
            field=models.CharField(max_length=256, verbose_name='Token Name'),
        ),
        migrations.AlterField(
            model_name='transaction',
            name='trades_for_maker',
            field=models.CharField(blank=True, max_length=16384, null=True, verbose_name='Transactions per Wallet'),
        ),
        migrations.AlterField(
            model_name='transaction',
            name='trades_makers',
            field=models.CharField(blank=True, max_length=16384, null=True, verbose_name='Trading Wallets'),
        ),
        migrations.AlterField(
            model_name='transaction',
            name='trades_sum',
            field=models.CharField(blank=True, max_length=16384, null=True, verbose_name='Operation Amounts'),
        ),
        migrations.AlterField(
            model_name='transaction',
            name='transactions',
            field=models.IntegerField(blank=True, null=True, verbose_name='Total Transactions'),
        ),
        migrations.AlterField(
            model_name='transaction',
            name='tt_bought',
            field=models.CharField(blank=True, max_length=2048, null=True, verbose_name='Top Trader Buys'),
        ),
        migrations.AlterField(
            model_name='transaction',
            name='tt_sold',
            field=models.CharField(blank=True, max_length=2048, null=True, verbose_name='Top Trader Sells'),
        ),
        migrations.AlterField(
            model_name='transaction',
            name='tt_speed',
            field=models.CharField(blank=True, max_length=2048, null=True, verbose_name='Top Trader Speed'),
        ),
        migrations.AlterField(
            model_name='transaction',
            name='tt_unrealized',
            field=models.CharField(blank=True, max_length=2048, null=True, verbose_name='Top Trader Unrealized Amount'),
        ),
        migrations.AlterField(
            model_name='transaction',
            name='twitter_days',
            field=models.IntegerField(blank=True, null=True, verbose_name='Twitter Age, days'),
        ),
        migrations.AlterField(
            model_name='transaction',
            name='twitter_followers',
            field=models.IntegerField(blank=True, null=True, verbose_name='Twitter Followers'),
        ),
        migrations.AlterField(
            model_name='transaction',
            name='twitter_smart_followers',
            field=models.IntegerField(blank=True, null=True, verbose_name='Twitter Smart Followers'),
        ),
        migrations.AlterField(
            model_name='transaction',
            name='twitter_tweets',
            field=models.IntegerField(blank=True, null=True, verbose_name='Twitter Posts'),
        ),
        migrations.AlterField(
            model_name='transaction',
            name='volume_h1',
            field=models.FloatField(blank=True, null=True, verbose_name='Trading Volume (1 hour), %'),
        ),
        migrations.AlterField(
            model_name='transaction',
            name='volume_h24',
            field=models.FloatField(blank=True, null=True, verbose_name='Trading Volume (24 hours), %'),
        ),
        migrations.AlterField(
            model_name='transaction',
            name='volume_h6',
            field=models.FloatField(blank=True, null=True, verbose_name='Trading Volume (6 hours), %'),
        ),
        migrations.AlterField(
            model_name='transaction',
            name='volume_m5',
            field=models.FloatField(blank=True, null=True, verbose_name='Trading Volume (5 minutes), %'),
        ),
    ]
